### ISSUE TITLE
Not work in iOS 9 & iOS 10

### ISSUE THREAD

**Issue by Michael-iOSer** [quentinfasquel/MyTransparentVideoExample#1]
I have some troubles in iOS 9 & iOS 10。The final video seems like to be stretched in iOS9 &iOS10 。and in iOS9，it have some shadow。applyingCIFiltersWithHandler seems like  not remove prevouis outputImage in iOS 9。

**Comment by quentinfasquel** [comment]
@Michael-iOSer I am sorry to answer almost one year later. I hadn't noticed this issue.
Someone else reported it and you will find an answer [here](https://github.com/quentinfasquel/MyTransparentVideoExample/issues/3#issuecomment-561518637)

**Comment by Michael-iOSer** [comment]
Thanks for you reply, My current solution  is use AVPlayerItemVideoOutput to get CVPixelBufferRef, then use the filter. i will try to see how to use SpriteKit

**Comment by ifananomali** [comment]
> Thanks for you reply, My current solution is use AVPlayerItemVideoOutput to get CVPixelBufferRef, then use the filter. i will try to see how to use SpriteKit

could you please show me how to fix it using AVPlayerItemVideoOutput? Thank you
